Make cachedMake work with local Nix install and proxy
NIX_PATH is no longer set for local Nix installs:
https://github.com/NixOS/nixpkgs/issues/149791
which was yielding the following error:

error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)